### ISSUE TITLE
Truly offline instance that does not depend on external services

### ISSUE THREAD

**Issue by lautriva** [awinterstein/habitica#11]
Hi, I just installed and tested your fork of Habitica today and it works great 🙂

But when taking a look at requests, I see some going to AWS (images) + google (fonts)

I see the repo contains an "habitica-images" submodule, so i'm assuming that assets are already here and it is probably only a missing setting on my side to use them

Here is my docker-compose file below
(I'm running it on my local server)

```
version: "3"
services:
  server:
    image: docker.io/awinterstein/habitica-server:latest
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - NODE_DB_URI=mongodb://mongo/habitica # this only needs to be adapted if using a separate database
      - BASE_URL=http://127.0.0.1:3000 # change this to the URL under which your instance will be reachable
      - INVITE_ONLY=true # change to `true` after registration of initial users, to restrict further registrations
      - EMAIL_SERVER_URL=mail.example.com
      - EMAIL_SERVER_PORT=587
      - EMAIL_SERVER_AUTH_USER=mail_user
      - EMAIL_SERVER_AUTH_PASSWORD=mail_password
      - ADMIN_EMAIL=mail@example.com # the sender address to send out emails
    ports:
      - "3000:3000"
    networks:
      - habitica
  mongo:
    image: docker.io/mongo:5.0
    restart: unless-stopped
    hostname: mongo
    command: ["--replSet", "rs", "--bind_ip_all", "--port", "27017"]
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate() }" | mongosh --port 27017 --quiet
      interval: 10s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - ./db:/data/db:rw
      - ./dbconf:/data/configdb
    networks:
      habitica:
        aliases:
          - mongo
networks:
  habitica:
    driver: bridge
```

![Image](https://github.com/user-attachments/assets/bfae1907-4b3f-434a-bf13-42b24e86c859)
