### ISSUE TITLE
Compose and SMTP issues

### ISSUE THREAD

**Issue by Saik0Shinigami** [awinterstein/habitica#4]
Hello! Thanks for packaging this up nicer for self-hosting first of all. But I end up with some questions here...

1) What's the point of the client? Removing the client all together and pointing a reverse proxy directly at the server at port 3000 seems to work just fine? Am I missing something? To me it seems like the "server" is also running the client software?

2) The compose contains a real problem if you ever down the container. When MongoDB sets up the replication it will take whatever hostname was assigned to it at the time replication was setup. When you down and up the container again that generic ID it was assigned will change. Adding a hostname and alias to the network config fixes this. Also makes keeping persistent database possible as a mounted volume.

3) Defining ports to expose on the database is probably not good for normal people... it doesn't need to be defined for containers on the same docker network to talk to each other. Less things exposed, less risk of abuse.

4)  I cannot for the life of me get SMTP to work. Many times I get template issues (invite-friend-guild and invite-friend templates are missing when I check the website/server/libs/emailSmtp.js file that has the templates they seem to have different names, probably invited-party and invited-guild). 

And other times it complains that it can't parse BASE_URL when it's present in the config and is valid for reaching the server. 
Full error: `{"fullError":{},"level":"error","message":"TypeError: Cannot read properties of undefined (reading 'BASE_URL')\n    at Object.text (/var/lib/habitica/website/transpiled-babel/libs/emailSmtp.js:38:74)\n    at /var/lib/habitica/website/transpiled-babel/libs/emailSmtp.js:511:83\n    at Array.forEach (<anonymous>)\n    at sendEmail (/var/lib/habitica/website/transpiled-babel/libs/emailSmtp.js:503:21)\n    at sendTxn (/var/lib/habitica/website/transpiled-babel/libs/email.js:144:35)\n    at /var/lib/habitica/website/transpiled-babel/libs/auth/index.js:276:26\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) unhandledPromiseRejection","promise":{},"timestamp":"2024-12-22T02:29:06.312Z"}`

The following is my current compose.yml:

```
services:
  server:
    image: docker.io/awinterstein/habitica-server:latest
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - NODE_DB_URI=mongodb://mongo/habitica
      - BASE_URL=https://habitica.<redacted>
      - INVITE_ONLY=false
      - EMAIL_SERVER_URL=mail.<redacted>
      - EMAIL_SERVER_PORT=25
      - EMAIL_SERVER_AUTH_USER=service@<redacted>
      - EMAIL_SERVER_AUTH_PASSWORD=<redacted>
    ports:
      - "3000:3000"
    networks:
      - habitica

  mongo:
    image: docker.io/mongo:5.0
    restart: unless-stopped
    hostname: mongo
    command: ["--replSet", "rs", "--bind_ip_all", "--port", "27017"]
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate() }" | mongosh --port 27017 --quiet
      interval: 10s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - ./db:/data/db:rw
      - ./dbconf:/data/configdb
    networks:
      habitica:
        aliases:
          - mongo

networks:
  habitica:
    driver: bridge
```
